language: node_js
before_script:
- yarn install
- mkdir dist
- yarn run build
node_js:
- node
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  target-branch: gh-pages
  on:
    branch: master
env:
  global:
    secure: g5KBx73xqiJOBv5AolJfhFoYCJJ4x5QRd3G4Py+mLyJeFIKcxBZ6CdR9v2X8FTsZ8usND6P/zpwI+O5bhDLSH7/zfubI8jepbfCHf8Vp/XpSoCrcxr+2j9JytHIZmGU2hBALcszbHlm4zD561U47iwIRE/vpZKZZiQJguZmtsYMxO1NQQeyDDl2ozR14o6Suw/6y4HnmSpejaTC8qUWSOGlkaa/n0jZvgfkFerC+TR6f+sVXOe81xgVB1QDmyUQX4/aOoyiV3NTP3lI6NzaZEalBgkAGWQ4D8EYlmpSUIeB3ba7wngdSi26SzwENrxk/1QDQ4PLGdEv1yetM0viuR2qjlqlorMcvjVEOLBJ5Bz+8IrH4M/GijTJoY4l8gbKRcxPySf4h+4GZ6x1aidv/OCuzB/t8/RMXS0kA1htfdzYLilM1veMHGQFgT6TWL4r9ExkjuAdfG/OCQDkIFfurk0mOJWdCeFfa4HSukH1e++OLDHUIgfGli7d7i/nSzg7wWN00gv5pysqoEj6UmR+BrDPTSYO8LUaRVMejoLhduGuWOYMS/YvvDNdp48P/XMJk2QnQjgPaX4gNkePl70kAvlNOBqGsoxWfY6PNAo+ATPUd7ve6jUHqmvSBnY/HIhnyQgnIEpQkiH1m0ZpvLy8qaAIjUmA27Us5IRV/5zAc0pM=
